// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4534.DeepSpace2019.subsystems;


import org.usfirst.frc4534.DeepSpace2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Solenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class PistonMove extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Solenoid solenoid1;
    private Solenoid altSolenoid1;
    private Solenoid solenoid2;
    private Solenoid solenoid3;
    private Solenoid solenoid4;
    private Solenoid solenoid5;
    private Solenoid solenoid6;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public PistonMove() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        solenoid1 = new Solenoid(0, 1);
        addChild("solenoid1", solenoid1);
        altSolenoid1 = new Solenoid(1);
        addChild("altSolenoid1", altSolenoid1);
        solenoid2 = new Solenoid(0, 2);
        addChild("solenoid2", solenoid2);
        solenoid3 = new Solenoid(0, 3);
        addChild("solenoid3", solenoid3);
        solenoid4 = new Solenoid(0, 4);
        addChild("solenoid4", solenoid4);
        solenoid5 = new Solenoid(0, 5);
        addChild("solenoid5", solenoid5);
        solenoid6 = new Solenoid(0, 6);
        addChild("solenoid6", solenoid6);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public boolean getSolenoid1(){
        return solenoid1.get();
    }
    public boolean getAltSolenoid1(){
        return altSolenoid1.get();
    }
    public boolean getSolenoid2(){
        return solenoid2.get();
    }
    public boolean getSolenoid3(){
        return solenoid3.get();
    }
    public boolean getSolenoid4(){
        return solenoid4.get();
    }
    public boolean getSolenoid5(){
        return solenoid5.get();
    }
    public boolean getSolenoid6(){
        return solenoid6.get();
    }
    public void setSolenoid1(boolean state){
        solenoid1.set(state);
    }
    public void setAltSolenoid1(boolean state){
        altSolenoid1.set(state);
    }
    public void setSolenoid2(boolean state){
        solenoid2.set(state);
    }
    public void setSolenoid3(boolean state){
        solenoid3.set(state);
    }
    public void setSolenoid4(boolean state){
        solenoid4.set(state);
    }
    public void setSolenoid5(boolean state){
        solenoid5.set(state);
    }
    public void setSolenoid6(boolean state){
        solenoid6.set(state);
    }
}

